baseURL = "https://rvnovae.com"
languageCode = "en-us"
title = "RvNovae"
theme = "papermod"

[markup.goldmark.renderer]
unsafe = true

[params.homeInfoParams]
Title = "RvNovae"
Content = """
Music producer, programmer
DE/EN/JP
"""

[params.profileMode]
enabled = true
subtitle = """
Music producer

DE/EN/JP
"""
imageUrl = "rvnovae.png"

[params.cover]
responsiveImages = true

[[menu.main]]
identifier = 'news'
name = 'Music News'
url = '/news'
[[menu.main]]
identifier = 'oliver'
name = 'Oliver Kogel'
url = '/oliver'

[[params.profileMode.buttons]]
name = "Music News"
url = "/news"
[[params.profileMode.buttons]]
name = "Oliver Kogel"
url = "/oliver"
[[params.profileMode.buttons]]
name = "Bandcamp"
url = "https://rvnovae.bandcamp.com"
[[params.profileMode.buttons]]
name = "ニコニコ"
url = "https://www.nicovideo.jp/user/68564602"

[[params.socialIcons]]
name = "youtube"
url = "https://youtube.com/rvnovae"
[[params.socialIcons]]
name = "spotify"
url = "https://open.spotify.com/artist/6bhBgsVfMHEP2uOgMrjXmH?si=9lZKhHn-Qya3eRfVPewfug"
[[params.socialIcons]]
name = "applemusic"
url = "https://music.apple.com/us/artist/rvnovae/1271020837"

[[params.socialIcons]]
name = "email"
url = "mailto:rvnovae@gmail.com"

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/rvnovae"
[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/rvnovae"
[[params.socialIcons]]
name = "threads"
url = "https://www.threads.net/@rvnovae"
[[params.socialIcons]]
name = "mastodon"
url = "https://vocalodon.net/web/accounts/225550"
[[params.socialIcons]]
name = "discord"
url = "https://discord.gg/ZKM26Dk"